#!/usr/bin/env python3
"""Generate the MkDocs Material site (docs/) from the course Markdown sources.

- Copies every chapter / lab / assessment / FAQ / cheat-sheet / workbook page
  into docs/ with rewritten relative links and Material-friendly navigation.
- Injects the DIAGRAMS figures into module and lab pages with captions.
- Writes index.md (homepage), downloads pages, projects, references, about,
  plus mkdocs.yml and custom CSS.
- Copies PDF/, PPTX/, DATA/ and DIAGRAMS/ into docs/assets/ so every download
  link works on GitHub Pages (only docs/ is deployed).

Idempotent: docs/ is fully regenerated on each run (safe to commit and to run
inside GitHub Actions before `mkdocs build --strict`).

Usage (from the course root):
    python tools/build_site.py
    mkdocs build --strict
"""
import os
import re
import shutil

COURSE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(COURSE, "docs")
MD = os.path.join(COURSE, "MARKDOWN")
LAB = os.path.join(COURSE, "LAB")

CHAPTERS = sorted(f for f in os.listdir(MD) if f.endswith(".md"))
LABS = sorted(f for f in os.listdir(LAB) if f.endswith(".md"))
ASSESS = {
    "MCQs.md": "Multiple-choice questions",
    "Short-Questions.md": "Short-answer questions",
    "Long-Questions.md": "Long-answer questions",
    "Viva-Questions.md": "Viva questions",
    "Case-Studies.md": "Case-based & data questions",
    "Answer-Key.md": "Instructor answer key",
}
GUIDE = {
    "WORKBOOK/GMO-Cloning-Gene-Expression-Lab-Workbook.md": ("workbook", "Lab workbook"),
    "CHEAT-SHEET/GMO-Cloning-Gene-Expression-Cheat-Sheet.md": ("cheat-sheet", "Cheat sheet"),
    "FAQ/GMO-Cloning-Gene-Expression-FAQs.md": ("faqs", "FAQs"),
}
ASSET_DIRS = ("DIAGRAMS", "PDF", "PPTX", "DATA")

# Figure captions (doubles as alt text - requirement: meaningful alt text).
FIGS = {
    "plasmid_map": "Anatomy of a cloning plasmid: origin of replication, selectable marker, multiple cloning site, promoter and terminator.",
    "restriction_cloning": "Restriction-enzyme cloning: the insert and vector are cut with compatible enzymes, then ligated directionally.",
    "cloning_workflow": "The complete molecular-cloning workflow, from target-gene identification to sequence-confirmed recombinant construct.",
    "selection_screening": "Selection versus screening versus validation: antibiotic selection, colony PCR screening and sequencing validation.",
    "gibson_assembly": "Gibson Assembly: a 5' exonuclease chews back ends, complementary overlaps anneal, polymerase and ligase seal the seams.",
    "golden_gate": "Golden Gate (type IIS) assembly: enzymes cut outside their recognition sites, creating programmable 4-bp overhangs for one-pot multi-part assembly.",
    "expression_cassette": "An expression cassette: promoter, translation-initiation context, open reading frame and terminator/polyadenylation signal.",
    "reporter_constructs": "Promoter-reporter, enhancer-reporter and fusion-reporter construct architectures.",
    "gmo_workflows": "Conceptual GMO generation workflows for bacteria, plants (Agrobacterium / biolistics) and animals.",
    "crispr_mechanism": "CRISPR-Cas9 targeting: guide RNA directs Cas9 to the PAM-adjacent target, creating a double-strand break.",
    "base_prime_editing": "Base editing and prime editing modify DNA without a double-strand break.",
    "grn_cascade": "A developmental gene-regulatory network cascade linking signaling, transcription factors and terminal target genes.",
    "morphogen_gradient": "A morphogen gradient patterned by production, diffusion and decay; threshold concentrations specify distinct cell fates.",
    "neural_tube_pattern": "Spatial gene-expression domains in the vertebrate neural tube generated by opposing Shh and BMP gradients.",
    "ish_workflow": "In situ hybridization workflow: probe design, hybridization, washing, detection and spatial interpretation.",
    "qpcr_workflow": "RT-qPCR workflow from RNA isolation to the delta-delta-Ct relative-expression calculation.",
    "rnaseq_workflow": "Bulk RNA-seq workflow: library preparation, sequencing, alignment/quantification and differential expression.",
    "scrnaseq_workflow": "Single-cell RNA-seq workflow: cell barcoding, library construction, clustering and cell-type annotation.",
    "spatial_workflow": "Spatial transcriptomics workflow: tissue sectioning, spatially barcoded capture, sequencing and spatial reconstruction.",
    "spatial_map_sim": "In-silico spatial expression map used in the computational labs (region markers and gradients).",
    "expression_heatmap": "A simulated developmental expression heatmap (genes x stages) of the kind analyzed in the data labs.",
}

MODULE_FIGS = {
    "01": ["cloning_workflow"],
    "02": ["plasmid_map", "cloning_workflow"],
    "03": ["plasmid_map", "selection_screening"],
    "04": ["restriction_cloning", "gibson_assembly", "golden_gate"],
    "05": ["expression_cassette", "reporter_constructs"],
    "06": ["gmo_workflows"],
    "07": ["crispr_mechanism", "base_prime_editing"],
    "08": ["grn_cascade", "morphogen_gradient"],
    "09": ["morphogen_gradient", "neural_tube_pattern"],
    "10": ["grn_cascade"],
    "11": ["ish_workflow", "qpcr_workflow", "rnaseq_workflow", "scrnaseq_workflow", "spatial_workflow"],
    "12": ["expression_heatmap", "spatial_map_sim"],
    "13": ["gmo_workflows", "crispr_mechanism"],
    "14": [],
    "15": ["base_prime_editing", "grn_cascade"],
}
LAB_FIGS = {
    "01": ["plasmid_map", "cloning_workflow"],
    "02": ["restriction_cloning"],
    "03": ["restriction_cloning", "selection_screening"],
    "04": ["selection_screening"],
    "05": ["qpcr_workflow", "expression_heatmap"],
    "06": ["reporter_constructs"],
    "07": ["ish_workflow", "spatial_map_sim"],
    "08": ["rnaseq_workflow", "scrnaseq_workflow", "spatial_workflow"],
    "09": ["cloning_workflow", "reporter_constructs"],
}
LAB_TYPES = {"01": "Simulation", "02": "Simulation / demo", "03": "Simulation (SOP-governed demo)",
             "04": "Simulation / computational", "05": "Computational", "06": "Simulation + demo",
             "07": "Simulation / image interpretation", "08": "Computational", "09": "Capstone project"}
MODULE_ICONS = ["dna", "content-cut", "shield-check", "puzzle", "gene", "leaf", "crystal-ball", "seedling",
                "map-marker", "sitemap", "microscope", "chart-heatmap", "school", "scale-balance", "rocket"]


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def write(path, text):
    full = os.path.join(DOCS, path)
    os.makedirs(os.path.dirname(full) or DOCS, exist_ok=True)
    with open(full, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("  wrote", path)


def title_of(path):
    """First '# ' heading, with a 'Module NN -' / 'Lab NN -' prefix stripped."""
    for line in read(path).splitlines():
        if line.startswith("# "):
            return re.sub(r"^# (Module \d+|Lab \d+) \S+ ", "# ", line)[2:].strip()
    return os.path.basename(path)


def slugify(text):
    text = re.sub(r"[^\w\s-]", "", text.lower())
    return re.sub(r"[\s_]+", "-", text).strip("-")


def find_heading_line(text, keywords):
    """Return the full heading text (without '##') of the first matching '##' heading."""
    for line in text.splitlines():
        if line.startswith("## ") and any(k in line.lower() for k in keywords):
            return line[3:].strip()
    return None


def strip_nav(text):
    """Remove the repository navigation blockquote block."""
    out, skipping = [], False
    emoji_line = re.compile(r"^> [\U0001F300-\U0001FAFF\u2753\u274C\u2705]")
    for line in text.splitlines():
        if line.startswith("> **Navigation:**"):
            skipping = True
            continue
        if skipping and emoji_line.match(line):
            continue
        skipping = False
        out.append(line)
    return re.sub(r"\n{3,}", "\n\n", "\n".join(out))


def asset_url(dest_dir, sub):
    """File-relative URL from a docs page directory to docs/assets/<sub>."""
    base = os.path.join(DOCS, dest_dir) if dest_dir else DOCS
    r = os.path.relpath(os.path.join(DOCS, "assets", sub), base)
    return r.replace(os.sep, "/")


def rewrite(text, src_rel, dest_dir):
    """Rewrite markdown links from repository-relative to site-relative paths."""
    src_dir = os.path.dirname(src_rel)
    unresolved = []

    def repl(m):
        label, target = m.group(1), m.group(2)
        if target.startswith(("#", "http://", "https://", "mailto:")):
            return f"[{label}]({target})"
        anchor = ""
        if "#" in target:
            target, anchor = target.split("#", 1)
            anchor = "#" + anchor
        if not target:
            return f"[{label}]({anchor})" if anchor else label
        t = target.replace("\\", "/")
        p = "../" if dest_dir else ""           # subdirectory pages need one extra step up

        if t.endswith("/"):                      # directory links (DATA folders)
            base = t.rstrip("/").split("/")[-1]
            page = {"DATA": "datasets", "DIAGRAMS": "diagrams"}.get(base, base)
            return f"[{label}]({p}downloads/{page}.md{anchor})"
        if t.endswith(".md"):
            name = t.split("/")[-1]
            if name == "README.md":
                return f"[{label}]({p}index.md{anchor})"
            if re.match(r"^\d{2}-", name):
                return f"[{label}]({p}modules/{name}{anchor})"
            if name.startswith("Lab-"):
                return f"[{label}]({p}labs/{name}{anchor})"
            if name in ASSESS:
                return f"[{label}]({p}assessment/{name}{anchor})"
            if name == "REFERENCES.md":
                return f"[{label}]({p}references.md{anchor})"
            if name == "BUILD_REPORT.md":
                return f"[{label}]({p}about.md{anchor})"
            for rel_src, (slug, _t) in GUIDE.items():
                if name == os.path.basename(rel_src):
                    return f"[{label}]({p}guide/{slug}.md{anchor})"
            # Any other markdown source: link into its repository location.
            src_path = os.path.normpath(os.path.join(src_dir, t))
            if os.path.isfile(os.path.join(COURSE, src_path)):
                r = os.path.relpath(os.path.join(COURSE, src_path), os.path.join(DOCS, dest_dir) if dest_dir else DOCS)
                return f"[{label}]({r.replace(os.sep, '/')}{anchor})"
            unresolved.append(t)
            return f"[{label}](#{slugify(label)})"
        # Binary / data asset (pptx, pdf, csv, txt, py ...) served from docs/assets/.
        m = re.match(r"^(?:\.\./)*(DATA|DIAGRAMS|PDF|PPTX)/(.+)$", t)
        if m:
            return f"[{label}]({asset_url(dest_dir, m.group(1) + '/' + m.group(2))}{anchor})"
        src_path = os.path.normpath(os.path.join(src_dir, t))
        if os.path.isfile(os.path.join(COURSE, src_path)):
            r = os.path.relpath(os.path.join(COURSE, src_path), os.path.join(DOCS, dest_dir) if dest_dir else DOCS)
            return f"[{label}]({r.replace(os.sep, '/')}{anchor})"
        unresolved.append(t)
        return f"[{label}](#{slugify(label)})"

    out = re.sub(r"\[([^\]]*)\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)", repl, text)
    return out, unresolved


def figures_block(fig_keys, dest_dir):
    if not fig_keys:
        return ""
    lines = ["## Figures", ""]
    for key in fig_keys:
        cap = FIGS.get(key, key.replace("_", " "))
        lines += ["<figure markdown>",
                  f"![{cap}]({asset_url(dest_dir, 'DIAGRAMS/' + key + '.png')})",
                  "",
                  f"*Figure - {cap}*",
                  "</figure>", ""]
    return "\n".join(lines) + "\n"


def module_footer(idx):
    prev_ch = CHAPTERS[idx - 1] if idx > 0 else None
    next_ch = CHAPTERS[idx + 1] if idx + 1 < len(CHAPTERS) else None
    lines = ["---", "",
             "## What you should know", "",
             "Review the learning objectives at the top of this module and the self-check or quick-check "
             "questions above. When you can meet every objective unaided, you are ready to continue.", "",
             "## What you should be able to do", "",
             "- Test yourself with the [multiple-choice questions](../assessment/MCQs.md) and the "
             "[short-answer](../assessment/Short-Questions.md) and [long-answer](../assessment/Long-Questions.md) "
             "questions for these topics.",
             "- Instructors: model answers are in the [answer key](../assessment/Answer-Key.md).",
             "- Quick revision: [cheat sheet](../guide/cheat-sheet.md) and [FAQs](../guide/faqs.md).",
             "- Hands-on practice: the [laboratory overview](../labs/index.md).", ""]
    nav = []
    if prev_ch:
        nav.append(f"[<- {title_of(os.path.join(MD, prev_ch))}](../modules/{prev_ch})")
    nav.append("[Course home](../index.md)")
    if next_ch:
        nav.append(f"[Continue to next module ->](../modules/{next_ch})")
    return "\n".join(lines) + "\n" + " &middot; ".join(nav) + "\n"


def generic_footer(dest_dir, extra=""):
    up = "../index.md" if dest_dir else "index.md"
    lines = ["---", ""]
    if dest_dir == "labs":
        lines += ["**Related resources:** [Lab workbook](../guide/workbook.md) · "
                  "[Cheat sheet](../guide/cheat-sheet.md) · [Datasets](../downloads/datasets.md) · "
                  "[Assessments](../assessment/index.md)", ""]
    lines.append(f"[Course home]({up})")
    return "\n".join(lines) + extra + "\n"


def page_from(src, dest_dir, fig_keys=(), module_num=None, dest_name=None):
    """Convert one source markdown file into a docs page."""
    src_rel = os.path.relpath(src, COURSE).replace(os.sep, "/")
    text = strip_nav(read(src))
    text, unresolved = rewrite(text, src_rel, dest_dir)
    if unresolved:
        print(f"  WARNING unresolved links in {src_rel}: {unresolved}")
    figs = figures_block(fig_keys, dest_dir)
    if figs:
        anchor_line = find_heading_line(
            text, ("self-check", "quick-check", "key points", "where this leads", "summary"))
        if anchor_line:
            idx = text.index(anchor_line)
            head = text.rfind("## ", 0, idx)
            text = text[:head] + figs + "\n" + text[head:]
        else:
            text = text.rstrip() + "\n\n" + figs
    text = re.sub(r"\n-{3,}\s*$", "", text)  # avoid adjacent horizontal rules with the footer
    if module_num:
        text += module_footer(CHAPTERS.index(os.path.basename(src)))
    else:
        text = text.rstrip() + "\n\n" + generic_footer(dest_dir)
    name = dest_name or os.path.basename(src)
    write(os.path.join(dest_dir, name) if dest_dir else name, text)


def build():
    if os.path.isdir(DOCS):
        shutil.rmtree(DOCS)
    os.makedirs(DOCS, exist_ok=True)

    # ------------------------------------------------------------------ home
    cards = []
    for i, ch in enumerate(CHAPTERS):
        t = title_of(os.path.join(MD, ch))
        n_figs = len(MODULE_FIGS.get(ch[:2], []))
        cards.append(f'<a class="modcard" href="modules/{os.path.splitext(ch)[0]}/" title="{t}">'
                     f':material-{MODULE_ICONS[i]}: **{ch[:2]} &middot; {t}**<br>'
                     f'<small>{n_figs} figure{"s" if n_figs != 1 else ""} - self-check questions</small></a>')

    home = f"""---
title: GMO, Cloning Techniques & Developmental and Spatial Gene Expression
description: A complete university-level Molecular Biology learning module - genetic engineering, cloning, CRISPR, developmental and spatial gene expression.
---

<div class="hero" markdown>

# GMO, Cloning Techniques & Developmental and Spatial Gene Expression

### A complete Molecular Biology learning module

A rigorous, self-contained teaching module for BS/MS students in Molecular Biology, Biotechnology,
Bioinformatics, Genetics, Microbiology and Biomedical Sciences. Learn the theory, follow the molecular
mechanisms, work through the simulated data, complete the labs, and revise with the cheat sheet,
FAQs and assessments.

[Start learning :material-arrow-right:](modules/{CHAPTERS[0]}){{ .md-button .md-button--primary }}
[Open the lab workbook :material-flask:](guide/workbook.md){{ .md-button }}
[Download the cheat sheet :material-download:](guide/cheat-sheet.md){{ .md-button }}
[View slides & PDFs :material-presentation:](downloads/index.md){{ .md-button }}

</div>

## Instructor

**Dr. Saira Azam** — Assistant Professor  
Centre of Excellence in Molecular Biology, University of the Punjab, Lahore

## How to use this site

<div class="grid cards" markdown>

- :material-map-marker-path: **Follow the learning path** - work through the modules in order;
  every module ends with practice questions and a link to the next one.
- :material-flask: **Do the labs** - nine exercises (simulation / computational / demonstration) with
  instructor keys in the [lab workbook](guide/workbook.md).
- :material-database: **Analyze the data** - all [datasets](downloads/datasets.md) are simulated,
  deterministic and clearly labeled.
- :material-check-decagram: **Assess yourself** - [MCQs](assessment/MCQs.md), short and long questions,
  viva, case studies and an instructor [answer key](assessment/Answer-Key.md).

</div>

## Modules

<div class="grid cards" markdown>

{chr(10).join(cards)}

</div>

## Learning path

```text
START HERE -> Fundamentals (01-02) -> Molecular cloning (03-04) -> Vectors, expression & reporters (05)
  -> GMO technology (06) -> CRISPR (07) -> Developmental gene expression (08-10)
  -> Spatial & temporal expression (09, 11) -> Experimental methods (11) -> Data analysis (12)
  -> Case studies (13) -> Ethics & biosafety (14) -> Advanced topics (15) -> Assessment
```

## Course resources

| Resource | Where |
|---|---|
| 9 laboratory exercises | [Laboratory overview](labs/index.md) |
| Lab workbook with keys & rubrics | [Lab workbook](guide/workbook.md) |
| Simulated datasets (cloning, expression, spatial) | [Datasets](downloads/datasets.md) |
| 107-slide lecture deck (PPTX) and five printable PDFs | [Downloads](downloads/index.md) |
| Assessment package + instructor answer key | [Assessments](assessment/index.md) |
| Semester projects | [Projects](projects.md) |
| References (~75 curated sources) | [References](references.md) |
"""
    write("index.md", home)

    # -------------------------------------------------------------- modules
    for ch in CHAPTERS:
        page_from(os.path.join(MD, ch), "modules", MODULE_FIGS.get(ch[:2], ()), module_num=ch[:2])

    # ----------------------------------------------------------------- labs
    lab_index = ["---", "title: Laboratory exercises", "---", "",
                 "# Laboratory section", "",
                 "Nine exercises that turn the theory into practice. Every lab states its type "
                 "**(Wet Lab / Simulation / Demonstration / Computational)**, its expected results, data tables, "
                 "viva questions and an instructor key in the [lab workbook](../guide/workbook.md). "
                 "Any wet-lab component must follow your institution's approved SOP and biosafety rules.", "",
                 "| Lab | Title | Type |", "|---|---|---|"]
    for lb in LABS:
        lab_index.append(f"| {lb[4:6]} | [**{title_of(os.path.join(LAB, lb))}**]({lb}) | {LAB_TYPES[lb[4:6]]} |")
    lab_index += ["", "## Downloads", "",
                  f"- [Lab workbook (markdown)](../guide/workbook.md) and "
                  f"[PDF]({asset_url('labs', 'PDF/Lab-Workbook.pdf')})",
                  "- [All datasets](../downloads/datasets.md)", ""]
    write("labs/index.md", "\n".join(lab_index))
    for lb in LABS:
        page_from(os.path.join(LAB, lb), "labs", LAB_FIGS.get(lb[4:6], ()))

    # ----------------------------------------------------------- assessment
    a_idx = ["---", "title: Assessments", "---", "", "# Assessment package", "",
             "Question banks spanning recall to evaluation, all backed by an "
             "[instructor answer key](Answer-Key.md). Students: attempt each section before opening the key.", "",
             "| Section | Questions | File |", "|---|---|---|",
             "| Multiple-choice | 50 | [MCQs](MCQs.md) |",
             "| Short-answer | 30 | [Short questions](Short-Questions.md) |",
             "| Long-answer | 20 | [Long questions](Long-Questions.md) |",
             "| Viva | 40 | [Viva questions](Viva-Questions.md) |",
             "| Case-based + data interpretation | 12 + 10 | [Case studies](Case-Studies.md) |",
             "| Instructor key | all | [Answer key](Answer-Key.md) |", ""]
    write("assessment/index.md", "\n".join(a_idx))
    for f in ASSESS:
        page_from(os.path.join(COURSE, "ASSESSMENT", f), "assessment")

    # ---------------------------------------------------------------- guide
    for rel_src, (slug, _t) in GUIDE.items():
        page_from(os.path.join(COURSE, rel_src), "guide", dest_name=slug + ".md")

    # ------------------------------------------------------------- projects
    proj = ["---", "title: Projects", "---", "", "# Semester projects", "",
            "Three capstone formats, all detailed in [Lab 09 - Capstone Project](labs/Lab-09-Capstone-Project.md). "
            "All tracks share a common spine: question -> design -> execution (simulated) -> synthesis -> defense.", "",
            "## Project 1 - Design a recombinant expression construct", "",
            "Design a complete conceptual plasmid: promoter, gene of interest, reporter/tag, selection marker and "
            "terminator. Deliverables: construct map, cloning plan, diagnostic-digest predictions and a validation "
            "plan. Supporting exercises: [Lab 01](labs/Lab-01-DNA-Cloning-Design.md), "
            "[Lab 02](labs/Lab-02-Restriction-Digestion.md).", "",
            "## Project 2 - Developmental gene-expression analysis", "",
            "Analyze the provided temporal/spatial datasets ([downloads](downloads/datasets.md)): qPCR time "
            "course, bulk RNA-seq, single-cell clusters and the spatial matrix. Deliver a reproducible notebook "
            "with figures and interpretation ([Lab 05](labs/Lab-05-Gene-Expression-Analysis.md), "
            "[Lab 08](labs/Lab-08-Computational-Gene-Expression.md)).", "",
            "## Project 3 - GMO case-study investigation", "",
            "Choose a real GMO (for example Bt crops, Golden Rice, recombinant insulin or a CRISPR-edited crop) and "
            "evaluate the genetic modification, molecular mechanism, intended benefit, evidence, risks, regulation "
            "and societal considerations using the four-layer framework from "
            "[Module 14](modules/14-Ethics-Biosafety-and-Regulation.md).", "",
            "## Evaluation rubric (all tracks)", "",
            "| Criterion | Weight |", "|---|---|",
            "| Scientific accuracy and terminology | 30% |",
            "| Design / analysis quality | 30% |",
            "| Interpretation and critical evaluation | 20% |",
            "| Clarity of report and presentation | 20% |", ""]
    write("projects.md", "\n".join(proj))

    # ------------------------------------------------------------ downloads
    dl = ["---", "title: Downloads & resources", "---", "",
          "# Downloads & resources", "",
          "Everything in the course is also stored as source files in the repository "
          "(`PDF/`, `PPTX/`, `DATA/`, `DIAGRAMS/`). The links below are served directly from this site.", "",
          "## Lecture slides", "",
          "- :material-presentation: [GMO_Cloning_Gene_Expression.pptx - 107 slides with speaker notes]"
          f"({asset_url('downloads', 'PPTX/GMO_Cloning_Gene_Expression.pptx')}) - regenerate with `PPTX/build_pptx.py`", "",
          "## PDFs", ""]
    for pdf, desc in [("Complete-Tutorial.pdf", "Complete tutorial (all 15 modules)"),
                      ("Lab-Workbook.pdf", "Lab workbook with instructor keys"),
                      ("Cheat-Sheet.pdf", "2-4 page revision cheat sheet"),
                      ("FAQs.pdf", "67 FAQs"),
                      ("Assessment.pdf", "Full assessment package + answer key")]:
        dl.append(f"- :material-file-pdf-box: [{pdf}]({asset_url('downloads', 'PDF/' + pdf)}) - {desc}")
    dl += ["", "## Datasets", "",
           "Simulated, deterministic, clearly labeled teaching data:",
           "",
           "- [Cloning data](cloning-data.md) - vector maps, digests, colony PCR (Labs 01-04)",
           "- [Gene-expression data](gene-expression-data.md) - qPCR, RNA-seq, single-cell, luciferase "
           "(Labs 05, 06, 08)",
           "- [Spatial-expression data](spatial-expression-data.md) - spatial matrix + coordinates "
           "(Labs 07, 08)", "",
           f"Regenerate everything with `python DATA/generate_datasets.py` "
           f"(script: [`generate_datasets.py`]({asset_url('downloads', 'DATA/generate_datasets.py')})).", "",
           "## Diagrams", "",
           "All 21 schematic teaching diagrams are embedded across the module and lab pages and collected in the "
           "[diagram gallery](diagrams.md).", "",
           "## Markdown sources", "",
           "Chapters: `MARKDOWN/` - Labs: `LAB/` - Workbook: `WORKBOOK/` - Cheat sheet: `CHEAT-SHEET/` - "
           "FAQ: `FAQ/` - Assessments: `ASSESSMENT/` - References: [`REFERENCES.md`](../references.md)", ""]
    write("downloads/index.md", "\n".join(dl))

    dsets = ["---", "title: All datasets", "---", "", "# All datasets", "",
             "All course datasets are **simulated for education** - biologically plausible, deterministic "
             "(seeded) and clearly labeled. They must not be cited as experimental data.", "",
             "| Collection | Used in | Contents |", "|---|---|---|",
             "| [Cloning data](cloning-data.md) | Labs 01-04 | Vector maps, digest predictions, colony-PCR results |",
             "| [Gene-expression data](gene-expression-data.md) | Labs 05, 06, 08 | qPCR time courses, bulk RNA-seq, "
             "single-cell matrix, dual-luciferase data |",
             "| [Spatial-expression data](spatial-expression-data.md) | Labs 07, 08 | Spot-gene spatial matrix, "
             "coordinates, region key |", "",
             f"Regenerate: `python DATA/generate_datasets.py` "
             f"([script]({asset_url('downloads', 'DATA/generate_datasets.py')})). "
             "A worked analysis walkthrough ships as "
             f"[`analysis_demo.py`]({asset_url('downloads', 'DATA/spatial-expression-data/analysis_demo.py')}).", ""]
    write("downloads/datasets.md", "\n".join(dsets))

    data_desc = {
        "cloning-data": ("Cloning data (Labs 01-04)",
                         "Vector maps, restriction-digest fragment predictions and colony-PCR screening results. "
                         "All simulated and deterministic (seeded)."),
        "gene-expression-data": ("Gene-expression data (Labs 05, 06, 08)",
                                 "qPCR time courses, bulk RNA-seq counts, a single-cell expression matrix, "
                                 "dual-luciferase reporter data and developmental expression profiles. All simulated."),
        "spatial-expression-data": ("Spatial-expression data (Labs 07, 08)",
                                    "Spot-by-gene spatial matrix, spot coordinates and a region key for the "
                                    "in-silico spatial maps. All simulated."),
    }
    for folder, (h, desc) in data_desc.items():
        rows = []
        for f in sorted(os.listdir(os.path.join(COURSE, "DATA", folder))):
            if f.startswith("."):
                continue
            kb = os.path.getsize(os.path.join(COURSE, "DATA", folder, f)) / 1024
            rows.append(f"| [`{f}`]({asset_url('downloads', 'DATA/' + folder + '/' + f)}) | {kb:.1f} KB |")
        text = (f"---\ntitle: {h}\n---\n\n# {h}\n\n{desc}\n\n## Files\n\n| File | Size |\n|---|---|\n"
                + "\n".join(rows)
                + f"\n\nStart from the analysis walkthrough in [Lab 08](../labs/Lab-08-Computational-Gene-Expression.md) "
                  f"and the bundled [`analysis_demo.py`]({asset_url('downloads', 'DATA/spatial-expression-data/analysis_demo.py')}).\n")
        write(f"downloads/{folder}.md", text)

    dgr = ["---", "title: Diagram gallery", "---", "", "# Diagram gallery", "",
           "All 21 programmatic teaching diagrams (matplotlib; regenerate with `DIAGRAMS/generate_diagrams.py`). "
           "Each is embedded in the relevant module and lab pages.", ""]
    for key, cap in FIGS.items():
        dgr += [f"![{cap}]({asset_url('downloads', 'DIAGRAMS/' + key + '.png')})", f"*{cap}*", ""]
    write("downloads/diagrams.md", "\n".join(dgr))

    # ----------------------------------------------------------- references
    refs = strip_nav(read(os.path.join(COURSE, "REFERENCES.md")))
    write("references.md", "---\ntitle: References\n---\n\n" + refs.rstrip()
          + "\n\n---\n\n[Course home](index.md)\n")

    # ---------------------------------------------------------------- about
    about = ["---", "title: About this course", "---", "",
             "# About this course", "",
             "**GMO, Cloning Techniques & Developmental and Spatial Gene Expression** is a complete, "
             "university-level teaching module assembled for direct classroom use by professors and self-study by "
             "students. The repository contains the full Markdown source, a 107-slide lecture deck, five printable "
             "PDFs, nine labs with instructor keys, 19 simulated datasets and a complete assessment package.", "",
             "## Instructor", "",
             "**Dr. Saira Azam** — Assistant Professor  ",
             "Centre of Excellence in Molecular Biology, University of the Punjab, Lahore.", "",
             "## Safety and responsible use", "",
             "This is an educational package. Wet-lab activities are framed as conceptual workflows or "
             "SOP-governed teaching procedures: institutions must supply approved protocols, biosafety approval and "
             "supervision for any hands-on component. No operational animal, viral-vector or plant-manipulation "
             "parameters are included by design.", "",
             "## License", "",
             "Released under the MIT License (see `LICENSE` in the repository). Reuse and adapt freely with "
             "attribution; the simulated datasets may not be cited as experimental data.", "",
             "## Build information", "",
             "The full content inventory and QA record is in `BUILD_REPORT.md` at the repository root.", ""]
    write("about.md", "\n".join(about))

    # ----------------------------------------------------------------- css
    write("stylesheets/extra.css", """
/* Course site styling */
.md-typeset .hero { text-align: center; padding: 2rem 1rem 1.5rem; border-radius: .4rem;
  background: linear-gradient(135deg, rgba(0,110,109,.14), rgba(0,150,136,.05)); }
.md-typeset .hero h1 { margin-bottom: .2rem; }
.md-typeset .hero .md-button { margin: .2rem; }
a.modcard { display: block; padding: .8rem 1rem; border: 1px solid var(--md-default-fg-color--lightest);
  border-radius: .4rem; color: var(--md-typeset-color); font-size: .8rem; }
a.modcard:hover { border-color: var(--md-primary-fg-color); box-shadow: 0 0 .4rem rgba(0,0,0,.08); }
.md-typeset figure { margin: 1em 0; text-align: center; }
.md-typeset figure img { max-width: 100%; border: 1px solid var(--md-default-fg-color--lightest);
  border-radius: .3rem; }
.md-typeset figcaption { font-size: .72rem; color: var(--md-default-fg-color--light); }
""")

    # ----------------------------------------------------------- mkdocs.yml
    chapter_nav = "\n".join(f'      - "{ch[:2]} - {title_of(os.path.join(MD, ch))}": modules/{ch}'
                            for ch in CHAPTERS)
    lab_nav = "\n".join(f'      - "{title_of(os.path.join(LAB, lb))}": labs/{lb}' for lb in LABS)
    assess_nav = "\n".join(f'      - "{f[:-3].replace("-", " ")}": assessment/{f}' for f in ASSESS)
    guide_nav = "\n".join(f'      - "{t}": guide/{s}.md'
                          for s, t in [("workbook", "Lab workbook"), ("cheat-sheet", "Cheat sheet"),
                                       ("faqs", "FAQs")])
    mk = f"""# MkDocs Material configuration for the course website.
# Project site: https://nadeem-majeedch.github.io/gmo-cloning-gene-expression/
site_name: GMO, Cloning Techniques & Developmental and Spatial Gene Expression
site_description: >-
  A complete university-level Molecular Biology teaching module: genetic engineering,
  molecular cloning, vectors, GMO generation, CRISPR, and developmental & spatial gene expression.
site_author: Course teaching team
repo_url: https://github.com/nadeem-majeedch/gmo-cloning-gene-expression
repo_name: nadeem-majeedch/gmo-cloning-gene-expression
site_url: https://nadeem-majeedch.github.io/gmo-cloning-gene-expression/
use_directory_urls: true
strict: true
docs_dir: docs
site_dir: site

theme:
  name: material
  language: en
  font: false
  logo: material/dna
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

extra_css:
  - stylesheets/extra.css

copyright: >
  <b>GMO, Cloning Techniques &amp; Developmental and Spatial Gene Expression</b> · Instructor:
  <b>Dr. Saira Azam</b>, Assistant Professor, Centre of Excellence in Molecular Biology,
  University of the Punjab, Lahore · Educational resource for academic teaching and learning
  under the MIT License — simulated datasets may not be cited as experimental data.

nav:
  - Home: index.md
  - Modules:
      - "Overview & learning path": index.md
{chapter_nav}
  - Laboratory:
      - "Overview": labs/index.md
{lab_nav}
  - Assessments:
      - "Overview": assessment/index.md
{assess_nav}
  - Projects: projects.md
  - Guide:
{guide_nav}
  - Downloads:
      - "Resources & downloads": downloads/index.md
      - "All datasets": downloads/datasets.md
      - "Cloning data": downloads/cloning-data.md
      - "Gene-expression data": downloads/gene-expression-data.md
      - "Spatial-expression data": downloads/spatial-expression-data.md
      - "Diagram gallery": downloads/diagrams.md
  - References: references.md
  - About: about.md
"""
    # mkdocs.yml must live at the course root, not inside docs/.
    write("../mkdocs.yml", mk)

    # ------------------------------------------------- copy binary assets in
    for d in ASSET_DIRS:
        src = os.path.join(COURSE, d)
        dst = os.path.join(DOCS, "assets", d)
        shutil.copytree(src, dst, ignore=shutil.ignore_patterns("__pycache__", ".ipynb_checkpoints", "README.md"))
        print("  copied", d, "-> docs/assets/" + d)
    print("done.")


if __name__ == "__main__":
    build()
